
name: Docker

on:
  workflow_dispatch:
  schedule:
    - cron: '00 23 * * *'

permissions:
  contents: write

jobs:
  download_installer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download installers
      run: |
         curl -o docker_linux.sh "https://get.docker.com"
         curl -o docker_windows_x86_64.exe "https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe"
         curl -o docker_mac_arm64.dmg "https://desktop.docker.com/mac/main/arm64/Docker.dmg"
         curl -o docker_mac_x84_64.dmg "https://desktop.docker.com/mac/main/amd64/Docker.dmg"
         curl -o docker_linux_debian_x84_64.dmg "https://desktop.docker.com/linux/main/amd64/149282/docker-desktop-4.30.0-amd64.deb"
         curl -o docker_linux_fedora_x84_64.dmg "https://desktop.docker.com/linux/main/amd64/149282/docker-desktop-4.30.0-x86_64.rpm"
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          docker_linux.sh
          docker_windows_x86_64.exe
          docker__mac_arm64.dmg
          docker_mac_x84_64.dmg
          docker_linux_debian_x84_64.dmg
          docker_linux_fedora_x84_64.dmg
        tag_name: latest
